[package]
name = "java_random_lcg"
version = "0.1.0"
authors = ["v31l-sys"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
